### PR TITLE
Readme explains how to run the .target file generation application via Maven/tycho-eclipse-plugin by providing a pom.xml snippet

### PR DESCRIPTION
**Pull request by daniel-matheis-vivavis**
updated README.textile:
adds a maven pom.xml snippet to run the .target file generation application via Maven/tycho-eclipse-plugin

### CODE REVIEW

**Comment by daniel-matheis-vivavis** [comment]
I wondered why this PR is not applied as it only represents a textual improvement:
seems the build is not functional although nothing should have changed there.
Maybe some insider can have a look here?


[ERROR] Failed to resolve target definition file:/home/jenkins/agent/workspace/targetplatform-dsl_PR-156/scm/org.eclipse.cbi.targetplatform.model/../target-platforms/default.target: Could not find "de.libutzki.xtext.nodemodeloutline.feature.feature.group/0.0.1.202110271659" in the repositories of the current location

**Comment by mbarbero** [comment]
It has not been merged because it slipped through the cracks. Sorry about that. I've restarted the CI build to verify if it's still failing. Thanks for the heads up.

**Comment by merks** [comment]
I'm not sure I got a notification about this at any point.  I get hundreds of emails per day from various git repositories, so I might have overlooked it.  Sorry sorry.

Could I ask that you change the commit subject to describe what this changes.   This should be in the body of the commit message not as the subject.
```
Fixes https://github.com/eclipse-cbi/targetplatform-dsl/issues/124
```

Thank of reading the list of changes here and needing to follow a link for each one just for an idea of what it's about:

https://github.com/eclipse-cbi/targetplatform-dsl/commits/master/

**Comment by merks** [comment]
The failure is of course unrelated to your changes:
```
org.eclipse.cbi.targetplatform.model/../target-platforms/default.target: Could not find "de.libutzki.xtext.nodemodeloutline.feature.feature.group/0.0.1.202110271659" in the repositories of the current location
```
I'll investigate.

**Comment by daniel-matheis-vivavis** [comment]
Thx for the feedback  - no reason to apologize !
Adapted the title to be more explanatory.

**Comment by merks** [comment]
If I read it correct, the commit looks like this:


image

And I'd rather see it as
```
Add a pom.xml snippet to the README.text

- Adds a maven pom.xml snippet to run the .target file generation application via Maven/tycho-eclipse-plugin

Fixes https://github.com/eclipse-cbi/targetplatform-dsl/issues/124

Signed-off-by: Daniel Matheis @ VIVAVIS <117902694+daniel-matheis-vivavis@users.noreply.github.com>
```

You'd need to amend and force put the commit to change it...

(I personally get frustrated when folks get so picky about the commit message, so hopefully this isn't annoying.)

**Comment by daniel-matheis-vivavis** [comment]
ah you wrote/meant the commit message...
i read too quickly and thought the title of this PR here
ok, will adapt the commit message as you proposed.

**Comment by merks** [comment]
FYI, I created this PR in case it's too much hassle:

https://github.com/eclipse-cbi/targetplatform-dsl/pull/158

I'm a bit too stupid to know how to contribute to an existing PR.  Either way is fine with me. 

Note that I fixed the build as well:

https://github.com/eclipse-cbi/targetplatform-dsl/pull/157

**Comment by daniel-matheis-vivavis** [comment]
Adapted commit message, pushed, build failed...

**Comment by merks** [comment]
Very good.  Thanks!  ❤️ 

You'd need to rebase for the build to work for the PR, but given this change has no build impact, that's not really relevant.  The actual ci builds are working fine:

https://ci.eclipse.org/cbi/view/p2RepoRelated/job/targetplatform-dsl/job/master/

**Comment by mbarbero** [comment]
Thanks Ed. You've been faster than me :) 

Thanks @daniel-matheis-vivavis for the contribution.

**Pull request merged**
