### PR TITLE
upgrade Maven dependencies

### PR DESCRIPTION
**Pull request by Bananeweizen**

### CODE REVIEW

**Comment by merks** [comment]
I think Tycho 3.x require Java 17 which needs to be changed in the Jenkinsfile used by the build.

**Comment by Bananeweizen** [comment]
@merks Arg, I keep forgetting that again and again on upgrading projects. Do Eclipse Jenkins machines even have `toolchains.xml` configured? Cause just running Tycho on 17 without pointing to the older installations via toolchains would lead to wrongly using the JDK 17 as EE11.

**Comment by Bananeweizen** [comment]
And it seems I'm not even allowed to modify the Jenkinsfile (which I understand from a security point of view):
```
Loading trusted files from base branch master at 95b45117f9cdafb3b43a0560a0a328e8ab4284e1 rather than 60651554f648dfef0309c133e3c77f008d1ed517
Obtained Jenkinsfile from 95b45117f9cdafb3b43a0560a0a328e8ab4284e1
‘Jenkinsfile’ has been modified in an untrusted revision
```
How are we supposed to make that a trusted revision then? I would guess my user account would need to be added somewhere in a Jenkins configuration?

**Comment by Bananeweizen** [comment]
@merks I've chosen 2.7.5 instead of 3.0.0 due to that trouble. Now it's green.

**Comment by merks** [comment]
Sorry I think I caused the conflict by processing this one first:

https://github.com/eclipse-cbi/targetplatform-dsl/pull/123

You can change the Java/Maven version of the build here:

https://github.com/eclipse-cbi/targetplatform-dsl/blob/7ce43ab10ffd91cebc25c1a74bf77a08a16258dc/Jenkinsfile#L12-L15

**Comment by Bananeweizen** [comment]
No problem, I had already expected a merge conflict. I could just have put the 2 commits in one PR, but I tend to prefer separation of concerns, even if it leads to such nasty merge conflicts.

**Comment by Bananeweizen** [comment]
I've raised https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2314 to check the repo needed by the build.

**Comment by merks** [comment]
Sorry I dropped the ball on this.

**Comment by Bananeweizen** [comment]
> Sorry I dropped the ball on this.

Ed, I fully understand your schedule is tight. No need to be sorry. Rather thanks for taking care of so many projects.

**Pull request merged**
