### PR TITLE
[#115] Fixed issue

### PR DESCRIPTION
**Pull request by hannesN**
* extended grammar
* extended XCore model
* created some resolved* model files
* extended generator for the maven elements
* created formatter for new DSL elements incl. test
* extended test dependencies so tests are running again
* created new target for 4.26
* extended default tpd for m2e bundles for testing
* modified keyword proposals so keywords are proposed for the maven elements
* created 2 new templates for the new location type

Signed-off-by: Hannes Niederhausen <hniederhausen@itemis.de>

### CODE REVIEW

**Comment by merks** [comment]
@hannesN 

Build using Java 17, I think you just need to change this line:

https://github.com/eclipse-cbi/targetplatform-dsl/blob/master/Jenkinsfile#L14

Currently 

> jdk 'openjdk-jdk11-latest'

Probably this works:

> jdk 'openjdk-jdk117-latest'

Or this:

> jdk 'temurin-jdk17-latest'

If the code you write needs Java 17 and fails for Java 11, you'll need to change the BREE each MANIFEST.MF.

**Comment by hannesN** [comment]
@merks I didn't want to change to much and for now we don't need m2e so Java17 is not mandatory. Would be nice to upgrade some day though. 

So who is reviewing such PRs anyways?

**Comment by merks** [comment]
@hannesN 

I'm not sure if @mbarbero wants to review things or if he is happy if I review things.  We both have limited time/capacity...  

Are the current changes in a state where you wish them to be merged?

**Comment by hannesN** [comment]
> @hannesN
> 
> I'm not sure if @mbarbero wants to review things or if he is happy if I review things. We both have limited time/capacity...
> 
> Are the current changes in a state where you wish them to be merged?

Yes, that's why I opened the PR :-)

I really like to see it in the snapshots, because I want to use it on my own. There is definitely more improvement possible, but my time as well is very limited, so I would rather see improvements implemented through new issues than let this PR be open for eternity.

**Comment by merks** [comment]
For me at least, it's easier if the changes are squashed so that I see a single commit with all the changes and see a nice commit title body.

Why was the 'Runtime Workspace.launch' removed?  I like to use that to launch an IDE in which I can try this stuff out in a self-hosted IDE...

Please add a copyright header to the two new *.java files you created.

Otherwise, it generally it looks very nice!!

**Comment by merks** [comment]
Hmm, squash and merge is not enabled:

image

I definitely don't want make these changes via 4 commits!

@mbarbero I guess have to open a help desk request to enabled squashing?

**Comment by hannesN** [comment]
Let me squash it in my repository, might be faster.

**Comment by hannesN** [comment]
> Please add a copyright header to the two new *.java files you created.
I added the comments, updated the launch config and squashed all in one commit.

Thanks for reviewing @merks

**Pull request merged**
