### PR TITLE
Use consistent indentation in the pom.xml files

### PR DESCRIPTION
**Pull request by miklossy**
Signed-off-by: Tamas Miklossy <miklossy@itemis.de>

### CODE REVIEW

**Comment by miklossy** [comment]
Unfortunately I do not have the rights to merge. @mbarbero Could you please merge?

**Comment by mbarbero** [comment]
I know. But github is having issues (https://githubstatus.com) and I can't merge for now.

**Comment by miklossy** [comment]
Ah ok, thanks for the hint.

**Comment by mbarbero** [comment]
(trying things to make github catch up with this one)

**Comment by miklossy** [comment]
I will close this PR and create a new one. Let's see if this helps.

**Pull request closed without merging**
